rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - rbx-head
  - rbx-head-d19
gemfile:
  - gemfiles/Gemfile-3.0
  - gemfiles/Gemfile-3.1
  - gemfiles/Gemfile-3.2
  - gemfiles/Gemfile-4.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-head
    - rvm: rbx-head-d19
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile-4.0
    - rvm: ree
      gemfile: gemfiles/Gemfile-4.0
    - rvm: rbx-head
      gemfile: gemfiles/Gemfile-4.0
